cbrnr/sleepecg

CHANGELOG.md, sleepecg/io/utils.py
`io.utils.download_file` calls itself to retry the download in case checksum verification fails. In case the "true" checksum is incorrect, this leads to an endless recursion stopped eventually by a `MemoryError`. I suggest to raise a `RuntimeError` instead of retrying. Alternatively, we could introduce a parameter to specify how many times the download should be retried.
=> Fix MemoryError in case of invalid checksum

.github/workflows/test.yml
The build+test workflow (in `test.yml`) is triggered on PRs. Currently, it builds wheels for cp37, cp38 and cp39 for each platform. To shorten workflow runtime (and save runner minutes), I'd suggest the following steps:
=> Faster build+test workflow

sleepecg/_heartbeat_detection.c, sleepecg/heartbeat_detection.py
Found two naming mistakes:
- `heartbeat_detection.py:95` mentions `scipy.signal.sosfilt`, although `sosfilfilt` is used (and causes the described issue)
- in `_heartbeat_detection.c:_squared_moving_integration` the pointer to the output array's data is called `beat_mask` (copy-paste error from `_thresholding`)
=> Fix incorrect names in heartbeat_detection

README.md
The array containing the detected peak indices is called `detection` for all detectors but the two from neurokit.
=> Fix naming inconsistencies in readme code listing

CHANGELOG.md, sleepecg/io/__init__.py, sleepecg/io/nsrr_api.py
The National Sleep Research Resource (NSRR) offers access to sleep datasets. A [ruby gem](https://github.com/nsrr/nsrr-gem) and an [R package](https://github.com/muschellij2/nsrr) are available, but I couldn't find a python interface.
=> Add interface to download NSRR data

.gitignore, .pre-commit-config.yaml, README.md, doc/Makefile, doc/make.bat, doc/requirements-doc.txt, doc/source/_templates/custom-class-template.rst, doc/source/_templates/custom-module-template.rst, doc/source/api.rst, doc/source/conf.py, doc/source/index.rst, readthedocs.yml, setup.cfg, sleepecg/__init__.py, sleepecg/heartbeat_detection.py, sleepecg/io/__init__.py, sleepecg/io/ecg_readers.py, sleepecg/io/nsrr_api.py, sleepecg/io/physionet_api.py, sleepecg/io/utils.py, sleepecg/tests/test_heartbeat_detection.py
Sphinx is set up to build a recursive autosummary for the API reference, i.e. each new public function will be added there automatically.
A test-build is avaiable [here](https://test-sleepecg.readthedocs.io/en/latest/).
TODO:
=> Provide API reference on readthedocs

CHANGELOG.md, setup.cfg, sleepecg/heartbeat_detection.py, sleepecg/tests/test_heartbeat_detection.py
`detect_heartbeats` is extended by anoptional argument `backend` to select which implementation to use. Backends `'c'` and `'numba'` can be selected only if the C extension or numba are available, respectively. If an unavailable backend is selected, the fallback order is `'c'` -> `'numba'` -> `'py'`.
=> Add py/numba implementation of heartbeat detection

sleepecg/heartbeats.py
They aren't required in the public API and this keeps the autogenerated documentation clean.
=> Make NamedTuples used as returnvalues non-public

sleepecg/heartbeats.py, sleepecg/io/ecg_readers.py, sleepecg/io/nsrr.py
I'd suggest we follow the [pandas docstring guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing_docstring.html#section-4-returns-or-yields) for documenting return values, since it's more specific than [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#returns) in that matter;
- for single return values, only the type is stated (no name)
- for multiple return values, both a name and a type are stated
- generators are treated similarly, so a type annotation `Iterator[int]` becomes just `int` in the docstring
=> Standardize return value docs

CHANGELOG.md, MANIFEST.in, doc/source/conf.py, setup.cfg, sleepecg/__init__.py, sleepecg/config.py, sleepecg/config.yml, sleepecg/globals.py, sleepecg/io/ecg_readers.py, sleepecg/test/test_config.py, sleepecg/test/test_heartbeats.py
This adds the possibility to store and retrieve configuration values which are stored under `~/.sleepecg/config.yml`, with default values sourced from `site-packages/sleepecg/config.yml`. The module `globals` is made obsolete and removed.
=> Add configuration interface

CHANGELOG.md, setup.cfg, sleepecg/io/__init__.py, sleepecg/io/sleep_readers.py, sleepecg/test/test_sleep_readers.py
Add a reader function for the [MESA](https://sleepdata.org/datasets/mesa) dataset. 
This PR also establishes the data structures which should be used by all other readers:
- `SleepRecord`: A `dataclass` for storing a single record consisting of heartbeat times and annotates stages.
- `SleepStage`: An `IntEnum` mapping AASM sleep stage identifiers to integers (will be required for classification and plotting).
=> Add `io.read_mesa`

doc/requirements-doc.txt, readthedocs.yml, setup.cfg
Building the docs on readthedocs is currently [failing](https://readthedocs.org/projects/sleepecg/builds/15421420/) because it attempts to install numpy 1.22.0rc1, which requires python 3.8. Using `pip` as the package installation method (instead of `setuptools`) and placing the doc requirements into an extras-section in `setup.cfg` (instead of `doc/requirements-doc.txt`) appears to fix that (see [this test build](https://readthedocs.org/projects/test-sleepecg/builds/15421560/)).
=> Fix failing readthedocs build

sleepecg/config.yml, sleepecg/test/test_examples.py, sleepecg/test/test_heartbeats.py, sleepecg/test/test_sleep_readers.py
To make sure the example scripts work... if an example should not be tested (e.g. because takes a long time, like the benchmark), it can be excluded by adding its name to `EXCLUDE` in `sleepecg/test/test_examples.py`.
=> Execute example scripts with pytest

CHANGELOG.md, sleepecg/io/__init__.py, sleepecg/io/nsrr.py, sleepecg/io/sleep_readers.py, sleepecg/test/test_sleep_readers.py
[SHHS](https://sleepdata.org/datasets/shhs)
This is pretty similar to `read_mesa`, except for the following differences:
- SHHS is grouped into two "visits" (there are two recorded nights for some participants), therefore there is an additional directory level (shhs1/shhs2).
- For MESA the ECG channel name is "EKG", for SHHS it's "ECG".
- SHHS does not include actigraphy data (while `read_mesa` doesn't read that data yet, this is planned).
Due to the similarity, large parts of `read_mesa` and `read_shhs` could be put into a new function. I'd like to postpone refactoring this until `read_mesa` handles actigraphy data and both functions handle metadata.
=> Add reader for SHHS

.github/workflows/test.yml
In case a commit/PR only changes files in `doc`, the build/test workflow doesn't need to run. This was already intended, but didn't happen due to a typo.
=> Skip test workflow on doc-only changes

CHANGELOG.md, doc/source/api.rst, doc/source/datasets.md, examples/benchmark/utils.py, examples/feature_extraction.py, examples/heartbeat_detection.py, sleepecg/__init__.py, sleepecg/feature_extraction.py, sleepecg/io/__init__.py, sleepecg/io/nsrr.py, sleepecg/io/sleep_readers.py, sleepecg/test/test_heartbeats.py, sleepecg/test/test_sleep_readers.py
To avoid situations like this:
```python
from sleepecg import extract_features
from sleepecg.io import read_mesa
```
I'd like to reduce the API to a single level, so one can do this:
```python
from sleepecg import extract_features, read_mesa
```
Also, to have `SleepRecord`, `SleepStage` and `ECGRecord` included and correctly linked in the docs, they are exported as well.
=> Export `sleepecg.io` members to main package 

sleepecg/feature_extraction.py
While working on the classification pipeline, I found 3 issues in the feature extraction code:
- The column indices used for selecting the requested features is not in the correct order, so the `feature_ids` returned by `extract_features` does not match the order of columns in the returned feature matrices.
- The calculation of `SD1` is missing a square root (see [hrvanalysis](https://github.com/Aura-healthcare/hrv-analysis/blob/master/hrvanalysis/extract_features.py#L539) and [Eq. 8 in this paper](https://psicolibra.it/wp-content/uploads/2013/10/nonlinear_features_of_heart_rate_variability.pdf) for reference).
- If a `SleepRecord` contains annotated `sleep_stages`, the feature matrix is missing 1 row. The subtraction in line 532 was originally intended to avoid having undefined sleep …
=> Fix mistakes in `feature_extraction`

sleepecg/utils.py
The warning should not be issued in cases where the user didn't request any parallelism.
=> Warn about joblib only if `n_jobs!=1`

CHANGELOG.md, examples/benchmark/benchmark_detectors.py, examples/benchmark/utils.py, sleepecg/io/ecg_readers.py, sleepecg/io/sleep_readers.py
In most cases, users will not want to pass `data_dir`, as it takes the value from the config file by default. Moving it to the end of the parameter list would allow to pass the record selection without a keyword, so instead of writing this:
```python
mesa = read_mesa(records_pattern='0001')
```
you could write this:
```python
mesa = read_mesa('0001')
```
=> Make `records_pattern` the first parameter of reader functions

CHANGELOG.md, examples/benchmark/utils.py
`data_dir` has to be passed as a keyword argument since #65 changed the order of arguments in the reader functions
fixes #67
=> Fix `reader_dispatch` not yielding anything

CHANGELOG.md, doc/source/api.rst, examples/benchmark/README.md, examples/benchmark/benchmark_detectors.py, sleepecg/io/__init__.py, sleepecg/io/ecg_readers.py
By default, the config option `export_records` is `False` so records only exported if explicitly requested.
=> Add option to export records in benchmark

CONTRIBUTING.md, README.md, doc/source/index.md, pyproject.toml, setup.cfg
Currently the optional dependencies are a bit of a mess:
- `full` should be what's needed for the full functionality of the package, but is actually not documented and just used for the CI tests
- `dev` contains `m2r2` which was made obsolete by switching to `myst-parser` in #36
- `dev` should contain everything needed for development (i.e. the full functionality, test and doc requirements), but doesn't
This fixes all of that and documents the different categories :)
=> Restructure and clarify extras_require

setup.cfg, sleepecg/test/test_sleep_readers.py
resolves #40 
The underlying issue was fixed in v0.1.24 but that version required NumPy>=1.22 (see holgern/pyedflib#164), so we should require v0.1.25 instead.
=> Require pyedflib v0.1.25 for tests

doc/source/conf.py, doc/source/feature_extraction.md
We use dollar math in our docs, so hopefully turning this on will render it, e.g. https://sleepecg.readthedocs.io/en/stable/feature_extraction.html#frequency-domain.
=> Enable MyST math parsing

CHANGELOG.md, sleepecg/feature_extraction.py
=> Improvements in preprocess_rri

.github/workflows/release.yml, .github/workflows/test.yml
I think it's best to always use `ubuntu-latest`, `windows-latest`, and `macos-latest`.
=> Use latest images in CI

sleepecg/io/ecg_readers.py
When downloading GUDB, records without annotations printed an HTTPError. This is confusing, because it looks like something went wrong when indeed such records are ignored. Fixes #108.
=> Do not print HTTP error for GUDB

examples/benchmark/benchmark_detectors.py
Since #114. the detector packages are imported inside `detector_dispatch`, making the first call to the function take longer than subsequent ones. To keep runtimes similar, each detector should run once before the actual benchmark, triggering the required imports.
=> Trigger imports at heartbeat detector benchmark start

CHANGELOG.md, sleepecg/heartbeats.py, sleepecg/test/test_feature_extraction.py, sleepecg/test/test_heartbeat_detection.py
Fixes https://github.com/cbrnr/sleepecg/issues/87
Flat data at the beginning of the ECG recording can mess up the Pan & Tompkins heartbeat detection. This PR adds a fix for that, such that the heartbeat detection only starts after the first non-flat sample of the data. The index of the first non flat sample is then added back to the array of heartbeat indices.
The overhead of calculating `np.nonzero(np.diff(ecg))[0]` is ~100 ms for a 8 hour ECG signal sampled at 256 Hz, on a 2019 MacBook Pro:
```python
%timeit np.nonzero(np.diff(np.random.rand(256 * 8 * 3600)))
```
I have also added unit tests and updated the changelog.
Feel free to edit,
Thanks,
Raphael
=> Handle flat data at the beginning of the recording

sleepecg/io/ecg_readers.py
In `gudb.GUDB_MD5`, filename keys use forward slashes. On windows, converting a `pathlib.Path` to a string produces backward slashes.
=> Fix GUDB checksum verification on windows

CHANGELOG.md, sleepecg/heartbeats.py
It could be that setting all values to zero before the first zero-crossing is not necessary (anymore). I'm currently running our benchmarks to see if it had any influence.
=> Remove zero-crossing check

CHANGELOG.md, sleepecg/config.py, sleepecg/test/test_config.py
If a user config file with entries is present, the loop variable `key` overwrites the function argument. Checking all keys at once avoids the name clash.
=> Fix bug where setting user config values lets get_config retrieve the wrong key

.gitignore, .pre-commit-config.yaml, examples/benchmark/utils.py, pyproject.toml, readthedocs.yml, setup.cfg, sleepecg/classification.py, sleepecg/config.py, sleepecg/feature_extraction.py, sleepecg/heartbeats.py, sleepecg/io/ecg_readers.py, sleepecg/io/gudb.py, sleepecg/io/nsrr.py, sleepecg/io/physionet.py, sleepecg/io/sleep_readers.py, sleepecg/io/utils.py, sleepecg/plot.py, sleepecg/test/test_sleep_readers.py, sleepecg/utils.py
=> Fix type errors

.github/workflows/release.yml, .github/workflows/test.yml, setup.cfg, sleepecg/test/test_heartbeats.py
I *think* cibuildwheel should already build 3.11 wheels, let's see...
=> Add Python 3.11 support

CHANGELOG.md, README.md, docs/index.md, setup.cfg, sleepecg/io/ecg_readers.py
If I remember correctly, `read_gudb` uses `pandas` because its `load_csv` used to be a lot faster than numpy's `loadtxt`. This changed in numpy 1.23.0 when the function [was implemented in C](https://numpy.org/doc/stable/release/1.23.0-notes.html#faster-np-loadtxt), so I guess we can drop pandas as an optional requirement. I don't think it's necessary to bump the required numpy version to 1.23.0 since it is just a speed improvement, not a functional one, what do you think @cbrnr?
=> remove dependency on pandas for read_gudb

docs/css/extra.css, mkdocs.yml
Until there is better support for MkDocs on RTD (see https://github.com/readthedocs/readthedocs.org/issues/9720), this workaround disables the flyout.
=> Workaround for RTD flyout not working

setup.cfg
Numba 0.57 with support for Python 3.11 is available.
=> Bump numba

setup.cfg
TensorFlow works with Python 3.11 on all platforms except macOS. Specifically, there is an optimized `tensorflow-macos` package, which leverages some optimized Apple APIs to make it faster, so we should require that package instead. I still need to test if this really works, I will report back.
=> Refine TensorFlow requirement

pyproject.toml, sleepecg/heartbeats.py, sleepecg/test/test_heartbeat_detection.py, sleepecg/test/test_sleep_readers.py
Trying to fix all warnings that occur in our tests. Not yet fully done, I need to ignore more DeprecationWarnings (that's the best we can do because they occur in external packages).
=> Fix warnings

sleepecg/test/test_heartbeats.py
With numba now available for python3.11 (#147), we can stop skipping the detect_heartbeats test with numba backend.
=> Test detect_heartbeats with numba backend on python 3.11

pyproject.toml
Using `tensorflow` instead of Apple-maintained `tensorflow-macos` and `tensorflow-metal` avoids problems when installing and loading models. This means no GPU support for Macs, but if someone really wants to enable this, it can be done manually (which means we don't have to support it).
=> Use official tensorflow package also on macOS

.flake8, .pre-commit-config.yaml, examples/benchmark/utils.py, examples/try_ws_gru_mesa.py, pyproject.toml, sleepecg/io/ecg_readers.py
This replaces flake8 with ruff, which is much faster and combines multiple tools (such as pydocstyle).
=> Replace flake8 with ruff

pyproject.toml
I forgot to do this when switching to Mkdocs.
=> Remove sphinx from dev requirements

readthedocs.yml
The `system_packages` setting is [deprecated](https://blog.readthedocs.com/drop-support-system-packages/), and I think we have never needed it in the first place.
=> Remove system packages from RTD build

pyproject.toml, sleepecg/test/test_heartbeats.py
I don't expect it to work, but let's see.
=> Check if Python 3.12 works

CHANGELOG.md, pyproject.toml
Numba 0.59 added support for Python 3.12, so let's see if this works.
=> Enable Numba on Python 3.12

.pre-commit-config.yaml, examples/benchmark/utils.py, pyproject.toml, sleepecg/classification.py, sleepecg/feature_extraction.py, sleepecg/io/ecg_readers.py, sleepecg/io/gudb.py, sleepecg/io/physionet.py, sleepecg/io/sleep_readers.py, sleepecg/utils.py
This PR simplifies `pyproject.toml` and uses `|` for type annotations. These are only available for Python ≥ 3.10, but we use them via `__future__`. Once we drop support for Python 3.9, these `__future__` imports can be removed.
=> Refresh project with latest style

CHANGELOG.md, src/sleepecg/plot.py
The previous function has apparently been removed in newer versions of Matplotlib.
=> Fix matplotlib colormap

CHANGELOG.md, docs/api/configuration.md, docs/configuration.md, examples/benchmark/utils.py, src/sleepecg/__init__.py, src/sleepecg/classification.py, src/sleepecg/config.py, src/sleepecg/io/ecg_readers.py, src/sleepecg/io/gudb.py, src/sleepecg/io/sleep_readers.py, src/sleepecg/io/utils.py, src/sleepecg/plot.py, tests/test_config.py
=> Fix some type checker warnings

CHANGELOG.md, docs/datasets.md, src/sleepecg/config.yml, src/sleepecg/io/nsrr.py, tests/test_nsrr.py
Added support for storing the nsrr_token in an environment variable or the config file of sleepecg. Since the nsrr_token can be set in multiple ways, the hierarchy for which nsrr_token is used is set as such:
1. using the nsrr_token set via the set_nsrr_token function defined in nsrr.py
2. using the nsrr_token set in an environment variable
3. using the nsrr_token set in the config file
Currently, sleepecg provides no functionality to set the nsrr_token as an environment variable or in the config file. Instead, these actions have to be performed by hand.
In addtion, the test_nsrr.py file was added introducing four test cases. Three cases cover the setting of the nsrr_token via methods 1-3 while the fourth test case covers an unset nsrr_token.
=> Support storing nsrr_token in config or environment variable

.github/workflows/release.yml, .github/workflows/test.yml
Workflows require approval until a PR has been merged (unless you tweak this setting), so get a tiny PR in first before putting in the real work and iteration in https://github.com/cbrnr/sleepecg/pull/251, otherwise the approval process will be a limiting factor
=> MAINT: Trivial CI bump

.github/workflows/cibuildwheel.yml, .pre-commit-config.yaml, CHANGELOG.md, README.md, pyproject.toml, readthedocs.yml, setup.py, src/sleepecg/utils.py, tests/test_heartbeats.py, tests/test_sleep_readers.py
In addition, bump dependencies.
=> Add support for Python 3.13

.github/workflows/cibuildwheel.yml, pyproject.toml, tests/test_heartbeats.py
Use the native runners, which should make it so tests can always run (in other repos it has been *faster* than the intel ones :face_with_open_eyes_and_hand_over_mouth: ).
=> ENH: Build aarch64 natively

CONTRIBUTING.md, pyproject.toml, setup.py, src/sleepecg/__init__.py
Instead of using a dynamic version, it is easier to put the actual version in `pyproject.toml` and then use `importlib.metadata.version()` to access it in SleepECG.
=> Remove dynamic version

.github/workflows/cibuildwheel.yml, pyproject.toml
Seems like this should be possible now.
=> Build arm64 and x86_64 wheels on macos-15
