.github/workflows/release.yml, .github/workflows/test.yml
=> Build ARM64 wheels for macOS

.github/workflows/release.yml
=> Include LICENSE in sdist

CONTRIBUTING.md, README.md, setup.cfg
=> Add contributing guide

README.md
=> Add conda to README.md

CHANGELOG.md, README.md, examples/benchmark/utils.py, examples/heartbeat_detection.py, sleepecg/io/__init__.py, sleepecg/io/ecg_readers.py, sleepecg/test/test_heartbeats.py
=> Separate reader functions per database

sleepecg/io/utils.py
=> List options for `checksum_type` in `download_file` docstring

CHANGELOG.md, sleepecg/io/__init__.py, sleepecg/io/sleep_readers.py, sleepecg/test/test_sleep_readers.py
Another sleep reader, this time for [SLPDB](https://physionet.org/content/slpdb/1.0.0/).
=> Add reader for SLPDB

.github/workflows/release.yml, .github/workflows/test.yml, pyproject.toml
Let's see how this affects the number of wheels that are built.
=> Use latest cibuildwheel version 2.3.0

pyproject.toml, sleepecg/_heartbeat_detection.c, sleepecg/heartbeats.py
Mostly very minor changes to make the comments more consistent and easier to follow.
=> Improve comments in heartbeats.py

sleepecg/heartbeats.py
Apparently a relict of the C code which can be simplified by NumPy mean and max functions.
=> Simplify learning phase 1 (Python)

doc/source/index.md, setup.cfg
Let's move away from matlab-terminology ;)
=> Change 'toolbox' to 'package'

examples/benchmark/README.md
Line 2 became outdated when restructuring the docs (#55).
Line 30 has always been wrong.
=> Fix links in heartbeat detection benchmark readme

doc/source/conf.py, doc/source/datasets.md, doc/source/index.md, setup.cfg
Preview for the discussion in #73
=> Change doc theme to furo

doc/source/conf.py
A few small changes:
- remove the year in the copyright notice to avoid updating it
- add a "last updated on" line to let users know the project is active
- remove the "author" variable in conf.py (this doesn't seem to be used anywhere)
@cbrnr, we talked about removing the word "Copyright", but since this requires a custom template, I'd like to keep it as-is.
=> Improve doc footer

CHANGELOG.md, doc/source/heartbeat_detection.md, sleepecg/heartbeats.py, sleepecg/test/test_heartbeat_detection.py
A quick PR for https://github.com/cbrnr/sleepecg/issues/88
Feel free to edit the documentation, rename the functions, etc
Thanks,
Raphael
=> Add more unit test + update documentation

doc/source/heartbeat_detection.md, sleepecg/heartbeats.py
Hi @cbrnr and @hofaflo,
I have just added some examples in the docstring of the functions. I think this will be useful. Feel free to edit the text.
Thanks,
Raphael
=> Improve docstring for heartbeats function

sleepecg/io/utils.py
=> Use assignment expression in checksum

doc/source/_static/custom.css, doc/source/api.rst, doc/source/conf.py, doc/source/heartbeat_detection.md
Add parentheses after functions, do not use the linkcode extension (Sphinx should be able to detect all module functions/classes automatically).
=> Tweak docs

doc/source/classification.md, doc/source/configuration.md, doc/source/feature_extraction.md, doc/source/heartbeat_detection.md
Mostly typos and minor modifications to make it easier to read. Fixes #101 as well.
=> Minor doc fixes

CHANGELOG.md, examples/benchmark/README.md, examples/benchmark/utils.py
=> Nest detector imports in benchmarks

CHANGELOG.md, sleepecg/io/ecg_readers.py, sleepecg/io/physionet.py, sleepecg/io/sleep_readers.py
=> Move data_dir parameter in download_physionet

docs/api/datasets.md, sleepecg/io/__init__.py, sleepecg/io/ecg_readers.py, sleepecg/io/gudb.py
=> Refactor inconsistencies

mkdocs.yml
WIP, it would be nice if the box could be reduced to just a magnifying glass icon.
=> Enable doc search

CHANGELOG.md, sleepecg/io/sleep_readers.py
I had some unicode decoding errors when reading SHHS data based on the windows "RIGHT SINGLE QUOTATION MARK" character. Changing the encoding to 'windows-1252' fixed this (as recommended in https://stackoverflow.com/a/40029793/3484157)
I also ran into some errors where gender or age values were missing for some rows in SHHS2 and I added the option for these parameters to be None.
I initially added logging for this, but removed it to avoid adding a new dependency (hence the multiple commits)
=> Update SHHS encoding style and missing data handling

CHANGELOG.md, sleepecg/feature_extraction.py, sleepecg/test/test_feature_extraction.py
=> Avoid excessive warnings during feature extraction

readthedocs.yml
Use ubuntu-22.04 and Python 3.11.
=> Update RTD image and Python

sleepecg/classification.py
Fixes #145. I've added a new parameter in case anyone wants to keep the messages (but by default they are now silenced).
=> Silence TensorFlow messages

CONTRIBUTING.md, README.md, docs/index.md
=> Escape square brackets

README.md, docs/index.md
=> Do not mention movement data

examples/try_ws_gru_mesa.py
=> Show plot in example

CHANGELOG.md, sleepecg/__init__.py, sleepecg/classification.py, sleepecg/feature_extraction.py, sleepecg/heartbeats.py, sleepecg/io/__init__.py, sleepecg/io/ecg_readers.py, sleepecg/io/gudb.py, sleepecg/io/nsrr.py, sleepecg/io/physionet.py, sleepecg/io/sleep_readers.py, sleepecg/plot.py, sleepecg/utils.py
=> Switch to absolute imports

docs/heartbeat_detection.md
=> Add missing np import in example

README.md, docs/heartbeat_detection.md
Add a short beat detection example (from the docs).
=> Add example to README.md

.pre-commit-config.yaml, pyproject.toml
=> Use ruff instead of black

README.md, docs/examples.md, docs/index.md, pyproject.toml
=> Bump Tensorflow (and other deps)

.github/workflows/release.yml, .github/workflows/test.yml
Hopefully this fixes the issue with v2.21.0...
=> Bump cibuildwheel to v2.21.1

CONTRIBUTING.md, README.md, docs/index.md
Remove dependency lists and some additional updates.
=> Update README and docs

tests/conftest.py, tests/test_config.py, tests/test_nsrr.py
- Move common fixture to `conftest.py`
- Use `monkeypatch` fixture for all patching
=> Optimize tests

.github/workflows/cibuildwheel.yml, pyproject.toml, readthedocs.yml
=> Bump images

.pre-commit-config.yaml, pyproject.toml, src/sleepecg/io/sleep_readers.py
Use latest versions of ruff and mypy.
=> Bump precommit actions

.pre-commit-config.yaml, pyproject.toml
Changes:
```
ruff (legacy alias)......................................................Passed
```
into:
```
ruff check...............................................................Passed
```
=> Update pre-commit ruff legacy alias

pyproject.toml
=> Use new license fields
